--para oracle utilizar desta forma
--INSERT INTO tbCST (id, cst, descricao, io, tipocst) VALUES((SELECT COUNT(*) + 1 FROM tbCST),Trim('000'),Trim('Nacional - Tributada integralmente'),null,2);

INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('000'),Trim('Nacional - Tributada integralmente'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('010'),Trim('Nacional - Tributada e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('020'),Trim('Nacional - Com redução de base de cálculo'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('030'),Trim('Nacional - Isenta ou não tributada e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('040'),Trim('Nacional - Isenta'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('041'),Trim('Nacional - Não tributada'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('050'),Trim('Nacional - Suspensão'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('051'),Trim('Nacional - Diferimento'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('060'),Trim('Nacional - ICMS cobrado anteriormente por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('070'),Trim('Nacional - Com redução de base de cálculo e cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('090'),Trim('Nacional - Outras'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('100'),Trim('Estrangeira - Importação direta - Tributada integralmente'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('110'),Trim('Estrangeira - Importação direta - Tributada e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('120'),Trim('Estrangeira - Importação direta - Com redução de base de cálculo'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('130'),Trim('Estrangeira - Importação direta - Isenta ou não tributada e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('140'),Trim('Estrangeira - Importação direta - Isenta'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('141'),Trim('Estrangeira - Importação direta - Não tributada'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('150'),Trim('Estrangeira - Importação direta - Suspensão'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('151'),Trim('Estrangeira - Importação direta - Diferimento'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('160'),Trim('Estrangeira - Importação direta - ICMS cobrado anteriormente por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('170'),Trim('Estrangeira - Importação direta - Com redução de base de cálculo e cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('190'),Trim('Estrangeira - Importação direta - Outras'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('200'),Trim('Estrangeira - Adquirida no mercado interno - Tributada integralmente'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('210'),Trim('Estrangeira - Adquirida no mercado interno - Tributada e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('220'),Trim('Estrangeira - Adquirida no mercado interno - Com redução de base de cálculo'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('230'),Trim('Estrangeira - Adquirida no mercado interno - Isenta ou não tributada e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('240'),Trim('Estrangeira - Adquirida no mercado interno - Isenta'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('241'),Trim('Estrangeira - Adquirida no mercado interno - Não tributada'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('250'),Trim('Estrangeira - Adquirida no mercado interno - Suspensão'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('251'),Trim('Estrangeira - Adquirida no mercado interno - Diferimento'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('260'),Trim('Estrangeira - Adquirida no mercado interno - ICMS cobrado anteriormente por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('270'),Trim('Estrangeira - Adquirida no mercado interno - Com redução de base de cálculo e cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('290'),Trim('Estrangeira - Adquirida no mercado interno - Outras'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('101'),Trim('Simples Nacional - Tributada pelo Simples Nacional com permissão de crédito'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('102'),Trim('Simples Nacional - Tributada pelo Simples Nacional sem permissão de crédito'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('103'),Trim('Simples Nacional - Isenção do ICMS no Simples Nacional para faixa de receita bruta'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('201'),Trim('Simples Nacional - Tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('202'),Trim('Simples Nacional - Tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('203'),Trim('Simples Nacional - Isenção do ICMS no Simples Nacional para faixa de receita bruta e com cobrança do ICMS por substituição tributária'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('300'),Trim('Simples Nacional - Imune'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('400'),Trim('Simples Nacional - Não tributada pelo Simples Nacional'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('500'),Trim('Simples Nacional - ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação'),0,2);
INSERT INTO tbCST (cst, descricao, io, tipocst) VALUES(Trim('900'),Trim('Simples Nacional - Outros'),0,2);